---
- hosts: routers
  gather_facts: false
  connection: local

  vars:
    cli:
      username: ans
      password: cisco123
  
  tasks:

    - name: get cdp information
      ios_command:
        provider: "{{cli}}"
        commands:
          - show cdp neighbor
      
      register: results

    - name: print output to screen
      debug:
        var=results.stdout_lines